---
framework: mocha
preRun:
  command:
    - npm ci
    - npm run compile
preMerge:
  pattern:
    - "./test/socket.io.ts"
postMerge:
  pattern: 
    - "./test/socket.io.ts"
postRun:
  command:
    - node --version
configFile: mocharc.yml
version: 1.0
