framework: mocha
preRun:
     command:
        - npm install
        - npm run compile && npm run test:types
preMerge:
  pattern:
    - "./test/socket.io.ts"
postMerge:
  pattern: 
    - "./test/socket.io.ts"
postRun:
     command:
        - node --version
configFile: "mocharc.yml"
version: 1.0
